import { useEffect, useMemo, useState } from "react";

type Page = "dashboard" | "clock" | "service-checks" | "departures" | "sae" | "parking" | "stats" | "fuel" | "leave" | "settings";
type Shift = { id:string; start:string; end?:string; note?:string };
type Drive = { id:string; shiftId:string; vehicle:string; start:string; end?:string; startKm:number; endKm?:number };
type Fuel = { id:string; driveId:string; vehicle:string; date:string; km:number; litres:number };
type Declared = { id:string; date:string; morningStart:string; morningEnd:string; afternoonStart:string; afternoonEnd:string; note:string };
type DayOff = { id:string; date:string; type:"Férié"|"Congé payé"|"Repos"; label:string };
type Settings = {
  overtimeMinutes:number; leaveN1:number; leaveN:number; vehicles:string[]; balanceStartDate:string;
  notionVehicle:string; notionLmjt:string; notionWednesday:string; notionHoliday:string;
  notionStops:string; notionDrivers:string; notionWork:string; notionDrive:string; notionFuel:string;
  notionSae:string; notionParking:string; notionServiceChecks:string;
};
type ServiceCheck = { id:string; time:string; qub:string; service:string; vehicle:string; driver:string; checked:boolean; hawk:string };
type ParkingSpot = { id:string; depot:string; spot:string; vehicle:string };

type Store = { shifts:Shift[]; drives:Drive[]; fuels:Fuel[]; declared:Declared[]; daysOff:DayOff[]; serviceChecks:ServiceCheck[]; parking:ParkingSpot[]; settings:Settings };

const DEFAULT_VEHICLES = ["AX-603-EJ","BG-309-BJ","BH-431-KH","BH-732-KH","BT-265-AF","BW-648-SW","GQ-655-WY","GV-989-MH","HB-009-AN","HB-342-AM","HB-640-AM"];
const DEFAULT_SERVICE_CHECKS:ServiceCheck[] = [
 {id:"svc-1",time:"05:55",qub:"463",service:"PVS Ligne 12.01",vehicle:"HB-342-AM",driver:"LORICOURT Alain",checked:false,hawk:"À contrôler"},
 {id:"svc-2",time:"06:24",qub:"471",service:"PVS Ligne 16.01",vehicle:"GQ-655-WY",driver:"BEVIN Sabrina",checked:false,hawk:"À contrôler"},
 {id:"svc-3",time:"07:05",qub:"446",service:"PVS Ligne 12.03",vehicle:"HB-640-AM",driver:"BEZIAU Sophie",checked:false,hawk:"À contrôler"},
 {id:"svc-4",time:"07:16",qub:"475",service:"PVS Ligne 17.01",vehicle:"GV-989-MH",driver:"ROME Laurent",checked:false,hawk:"À contrôler"},
 {id:"svc-5",time:"07:20",qub:"—",service:"P140.02",vehicle:"",driver:"Conducteur à affecter",checked:false,hawk:"Non identifié"}
];
const DEFAULT_PARKING:ParkingSpot[] = DEFAULT_VEHICLES.map((vehicle,index)=>({id:`park-${index+1}`,depot:index<7?"Lestonan":"Gourvily",spot:`${index<7?"Lestonan":"Gourvily"} ${index<7?index+1:index-6}`,vehicle}));
const DEFAULT_SETTINGS:Settings = { overtimeMinutes:0, leaveN1:25.5, leaveN:2.5, vehicles:DEFAULT_VEHICLES, balanceStartDate:new Date().toISOString().slice(0,10), notionVehicle:"", notionLmjt:"", notionWednesday:"", notionHoliday:"", notionStops:"", notionDrivers:"", notionWork:"", notionDrive:"", notionFuel:"", notionSae:"", notionParking:"", notionServiceChecks:"" };
const KEY = "depotdash-v1";
const DAILY=450, WEEKLY=2250, YEARLY=117000;

const readStore=():Store=>{ try { const raw=localStorage.getItem(KEY); if(raw){ const p=JSON.parse(raw); return {shifts:p.shifts||[],drives:p.drives||[],fuels:p.fuels||[],declared:p.declared||[],daysOff:p.daysOff||[],serviceChecks:p.serviceChecks?.length?p.serviceChecks:DEFAULT_SERVICE_CHECKS,parking:p.parking?.length?p.parking:DEFAULT_PARKING,settings:{...DEFAULT_SETTINGS,...p.settings,balanceStartDate:p.settings?.balanceStartDate||new Date().toISOString().slice(0,10),vehicles:p.settings?.vehicles?.length?p.settings.vehicles:DEFAULT_VEHICLES}}; } } catch{} return {shifts:[],drives:[],fuels:[],declared:[],daysOff:[],serviceChecks:DEFAULT_SERVICE_CHECKS,parking:DEFAULT_PARKING,settings:DEFAULT_SETTINGS}; };
const uid=()=>crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const ms=(a:string,b?:string,now=Date.now())=>(b?new Date(b).getTime():now)-new Date(a).getTime();
const mins=(n:number)=>Math.round(n/60000);
const fmtMin=(m:number,sign=false)=>{const s=m<0?"-":sign&&m>0?"+":""; const a=Math.abs(Math.round(m)); return `${s}${Math.floor(a/60)}h${String(a%60).padStart(2,"0")}`};
const fmtDur=(v:number)=>{const s=Math.max(0,Math.floor(v/1000));return [Math.floor(s/3600),Math.floor((s%3600)/60),s%60].map(n=>String(n).padStart(2,"0")).join(":")};
const localDate=(d=new Date())=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
const dateLabel=(s:string)=>new Intl.DateTimeFormat("fr-FR",{weekday:"short",day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${s}T12:00:00`));
const dateTime=(s:string)=>new Intl.DateTimeFormat("fr-FR",{dateStyle:"short",timeStyle:"short"}).format(new Date(s));
const rangeMins=(a:string,b:string)=>a&&b?Math.max(0,(+b.slice(0,2)*60+ +b.slice(3))-(+a.slice(0,2)*60+ +a.slice(3))):0;
const startOfWeek=(d:Date)=>{const x=new Date(d); const day=x.getDay()||7;x.setDate(x.getDate()-day+1);x.setHours(0,0,0,0);return x};
const inRange=(iso:string,a:Date,b:Date)=>{const d=new Date(iso);return d>=a&&d<=b};

function App(){
 const [store,setStore]=useState<Store>(readStore); const [page,setPage]=useState<Page>("dashboard"); const [now,setNow]=useState(Date.now()); const [toast,setToast]=useState("");
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(store))},[store]);
 useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(i)},[]);
 const activeShift=store.shifts.find(x=>!x.end); const activeDrive=store.drives.find(x=>!x.end);
 const update=(fn:(s:Store)=>Store,msg?:string)=>{setStore(fn); if(msg){setToast(msg);setTimeout(()=>setToast(""),2500)}};
 const today=localDate();
 const summary=useMemo(()=>calcStats(store,now),[store,now]);
 const pages:{key:Page;icon:string;label:string}[]=[{key:"dashboard",icon:"⌂",label:"Tableau de bord"},{key:"clock",icon:"◴",label:"Ma pointeuse"},{key:"service-checks",icon:"☑",label:"Prises de service"},{key:"departures",icon:"▤",label:"Prochains départs"},{key:"sae",icon:"◉",label:"SAE"},{key:"parking",icon:"P",label:"Parking"},{key:"stats",icon:"↗",label:"Statistiques"},{key:"fuel",icon:"⛽",label:"Carburant"},{key:"leave",icon:"▣",label:"Congés & jours fériés"},{key:"settings",icon:"⚙",label:"Paramètres"}];
 return <div className="shell">
  <aside><div className="brand"><div className="sun">☀</div><div><b>DepotDash</b><small>Centre opérationnel<br/>Océlorn</small></div></div><nav>{pages.map(p=><button key={p.key} className={page===p.key?"active":""} onClick={()=>setPage(p.key)}><span>{p.icon}</span>{p.label}</button>)}</nav><div className="aside-foot">Données enregistrées sur cet appareil</div></aside>
  <main><header><div><h1>{pages.find(p=>p.key===page)?.label}</h1><p>{page==="clock"?"Temps de travail, conduite et kilométrages":"Gestion personnelle du dépôt"}</p></div><span className="status">{activeShift?"● En service":"Hors service"}</span></header>
  {toast&&<div className="toast">{toast}</div>}
  {page==="dashboard"&&<Dashboard stats={summary} settings={store.settings} setPage={setPage}/>} 
  {page==="clock"&&<Clock store={store} now={now} update={update} activeShift={activeShift} activeDrive={activeDrive}/>} 
  {page==="service-checks"&&<ServiceChecksPage store={store} update={update}/>} 
  {page==="departures"&&<DeparturesPage store={store}/>} 
  {page==="sae"&&<SaePage store={store}/>} 
  {page==="parking"&&<ParkingPage store={store} update={update}/>} 
  {page==="stats"&&<Stats stats={summary}/>} 
  {page==="fuel"&&<FuelPage store={store} update={update}/>} 
  {page==="leave"&&<LeavePage store={store} update={update}/>} 
  {page==="settings"&&<SettingsPage store={store} update={update}/>} 
  </main>
 </div>
}

function Dashboard({stats,settings,setPage}:{stats:ReturnType<typeof calcStats>;settings:Settings;setPage:(p:Page)=>void}){
 const leave=settings.leaveN1+settings.leaveN; return <>
 <section className="hero"><div><span className="kicker">Aujourd’hui</span><h2>Bonjour Florian</h2><p>Votre situation de travail en un coup d’œil.</p></div><button className="primary" onClick={()=>setPage("clock")}>Ouvrir la pointeuse</button></section>
 <section className="cards four"><Metric title="Heures supplémentaires" value={fmtMin(settings.overtimeMinutes+stats.sinceStart.balance,true)} text="solde actuel" good/><Metric title="Congés payés" value={`${leave.toFixed(1)} j`} text={`N-1 : ${settings.leaveN1.toFixed(1)} · N : ${settings.leaveN.toFixed(1)}`}/><Metric title="Travail cette semaine" value={fmtMin(stats.week.work)} text={`${fmtMin(stats.week.due)} attendues`}/><Metric title="Conduite cette semaine" value={fmtMin(stats.week.drive)} text={`${stats.week.km} km`}/></section>
 <section className="panel"><h3>Configuration Notion</h3><p className="muted">Les liens sont enregistrés. La lecture automatique des bases privées sera activée lors de la connexion API sécurisée.</p><div className="notion-grid"><span>Véhicules</span><b>{settings.notionVehicle?"Configurée":"À configurer"}</b><span>Services scolaires</span><b>{settings.notionLmjt||settings.notionWednesday?"Configurés":"À configurer"}</b><span>Samedi + vacances</span><b>{settings.notionHoliday?"Configurée":"À configurer"}</b></div><button className="secondary" onClick={()=>setPage("settings")}>Ouvrir les paramètres</button></section>
 </>
}
function Metric({title,value,text,good}:{title:string;value:string;text:string;good?:boolean}){return <article className="metric"><span>{title}</span><strong className={good?"green":""}>{value}</strong><p>{text}</p></article>}

function Clock({store,now,update,activeShift,activeDrive}:{store:Store;now:number;update:(f:(s:Store)=>Store,m?:string)=>void;activeShift?:Shift;activeDrive?:Drive}){
 const [vehicle,setVehicle]=useState("");const[startKm,setStartKm]=useState("");const[endKm,setEndKm]=useState("");const[fuelKm,setFuelKm]=useState("");const[litres,setLitres]=useState("");const[showFuel,setShowFuel]=useState(false);const[edit,setEdit]=useState<{kind:"shift"|"drive";id:string}|null>(null);
 const driveMs=activeDrive?ms(activeDrive.start,undefined,now):0; const shiftMs=activeShift?ms(activeShift.start,undefined,now):0;
 const startShift=()=>update(s=>({...s,shifts:[{id:uid(),start:new Date().toISOString()},...s.shifts]}),"Prise de service enregistrée");
 const stopShift=()=>{if(activeDrive)return alert("Terminez la conduite avant de quitter le service.");update(s=>({...s,shifts:s.shifts.map(x=>x.id===activeShift?.id?{...x,end:new Date().toISOString()}:x)}),"Fin de service enregistrée")};
 const startDrive=()=>{if(!activeShift)return;if(!vehicle||!startKm)return alert("Choisissez un véhicule et indiquez le kilométrage.");update(s=>({...s,drives:[{id:uid(),shiftId:activeShift.id,vehicle,start:new Date().toISOString(),startKm:+startKm},...s.drives]}),"Conduite démarrée")};
 const stopDrive=()=>{if(!activeDrive||!endKm||+endKm<activeDrive.startKm)return alert("Kilométrage d’arrivée invalide.");update(s=>({...s,drives:s.drives.map(x=>x.id===activeDrive.id?{...x,end:new Date().toISOString(),endKm:+endKm}:x)}),"Conduite terminée");setVehicle("");setStartKm("");setEndKm("")};
 const addFuel=()=>{if(!activeDrive||!fuelKm||!litres)return;update(s=>({...s,fuels:[{id:uid(),driveId:activeDrive.id,vehicle:activeDrive.vehicle,date:new Date().toISOString(),km:+fuelKm,litres:+litres},...s.fuels]}),"Plein enregistré");setFuelKm("");setLitres("");setShowFuel(false)};
 return <>
 <section className="cards three"><Metric title="Temps de service en cours" value={fmtDur(shiftMs)} text={activeShift?`Depuis ${dateTime(activeShift.start)}`:"Hors service"}/><Metric title="Conduite en cours" value={fmtDur(driveMs)} text={activeDrive?activeDrive.vehicle:"Aucune conduite"}/><Metric title="Distance totale" value={`${store.drives.reduce((t,d)=>t+(d.endKm?Math.max(0,d.endKm-d.startKm):0),0)} km`} text="sessions terminées"/></section>
 <section className="panel clock"><div className="panel-head"><div><span className="kicker">Activité du jour</span><h3>Pointeuse personnelle</h3></div><span className={activeShift?"pill good":"pill"}>{activeShift?"● En service":"Hors service"}</span></div>
 {!activeShift?<button className="primary wide" onClick={startShift}>Prendre mon service</button>:<>
 {!activeDrive?<div className="form-grid"><label>Véhicule<select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">Choisir un véhicule</option>{store.settings.vehicles.map(v=><option key={v}>{v}</option>)}</select></label><label>Kilométrage de départ<input type="number" value={startKm} onChange={e=>setStartKm(e.target.value)} placeholder="Ex. 471448"/></label><button className="primary" onClick={startDrive}>Démarrer la conduite</button></div>:<div className="drive-live"><div><span>Véhicule</span><strong>{activeDrive.vehicle}</strong><p>Départ : {activeDrive.startKm.toLocaleString("fr-FR")} km</p></div><label>Kilométrage d’arrivée<input type="number" value={endKm} onChange={e=>setEndKm(e.target.value)}/></label><button className="danger" onClick={stopDrive}>Terminer la conduite</button><button className="secondary" onClick={()=>setShowFuel(!showFuel)}>⛽ Enregistrer un plein</button>{showFuel&&<div className="fuel-inline"><label>Km au plein<input type="number" value={fuelKm} onChange={e=>setFuelKm(e.target.value)}/></label><label>Litres<input type="number" step=".01" value={litres} onChange={e=>setLitres(e.target.value)}/></label><button className="primary" onClick={addFuel}>Ajouter</button></div>}</div>}
 <button className="secondary wide" onClick={stopShift}>Quitter mon service</button></>}
 </section>
 <DeclaredPanel store={store} update={update}/>
 <section className="panel"><h3>Historique des temps de travail</h3><div className="list">{store.shifts.map(s=><div className="row" key={s.id}><div><b>{dateTime(s.start)}</b><small>{s.end?`Fin : ${dateTime(s.end)}`:"Session en cours"}</small></div><div><span>Service</span><b>{fmtDur(ms(s.start,s.end,now))}</b></div><div><span>Conduite</span><b>{fmtMin(store.drives.filter(d=>d.shiftId===s.id).reduce((t,d)=>t+mins(ms(d.start,d.end,now)),0))}</b></div><div className="actions"><button onClick={()=>setEdit({kind:"shift",id:s.id})}>Modifier</button>{s.end&&<button className="trash" onClick={()=>confirm("Supprimer cette session ?")&&update(x=>({...x,shifts:x.shifts.filter(q=>q.id!==s.id),drives:x.drives.filter(q=>q.shiftId!==s.id)}),"Session supprimée")}>Supprimer</button>}</div></div>)}</div></section>
 <section className="panel"><h3>Sessions de conduite</h3><div className="list">{store.drives.map(d=><div className="row" key={d.id}><div><b>{d.vehicle}</b><small>{dateTime(d.start)}{d.end?` → ${dateTime(d.end)}`:" · en cours"}</small></div><div><span>Durée</span><b>{fmtDur(ms(d.start,d.end,now))}</b></div><div><span>Distance</span><b>{d.endKm?`${d.endKm-d.startKm} km`:"—"}</b></div><div className="actions"><button onClick={()=>setEdit({kind:"drive",id:d.id})}>Modifier</button>{d.end&&<button className="trash" onClick={()=>confirm("Supprimer cette conduite ?")&&update(x=>({...x,drives:x.drives.filter(q=>q.id!==d.id),fuels:x.fuels.filter(q=>q.driveId!==d.id)}),"Conduite supprimée")}>Supprimer</button>}</div></div>)}</div></section>
 {edit&&<EditDialog store={store} edit={edit} close={()=>setEdit(null)} update={update}/>}</>
}

function DeclaredPanel({store,update}:{store:Store;update:(f:(s:Store)=>Store,m?:string)=>void}){const [date,setDate]=useState(localDate());const [a,setA]=useState("06:30"),[b,setB]=useState("10:30"),[c,setC]=useState("14:30"),[d,setD]=useState("18:00"),[note,setNote]=useState("");const total=rangeMins(a,b)+rangeMins(c,d);const save=()=>update(s=>({...s,declared:[{id:s.declared.find(x=>x.date===date)?.id||uid(),date,morningStart:a,morningEnd:b,afternoonStart:c,afternoonEnd:d,note},...s.declared.filter(x=>x.date!==date)]}),"Horaires déclarés");return <section className="panel"><h3>Horaires déclarés</h3><div className="declared"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><fieldset><legend>Matin</legend><label>Début<input type="time" value={a} onChange={e=>setA(e.target.value)}/></label><label>Fin<input type="time" value={b} onChange={e=>setB(e.target.value)}/></label></fieldset><fieldset><legend>Après-midi / soirée</legend><label>Début<input type="time" value={c} onChange={e=>setC(e.target.value)}/></label><label>Fin<input type="time" value={d} onChange={e=>setD(e.target.value)}/></label></fieldset><label>Note<input value={note} onChange={e=>setNote(e.target.value)}/></label><div className="save-line"><b>Total : {fmtMin(total)}</b><button className="primary" onClick={save}>Enregistrer</button></div></div><div className="compact-list">{store.declared.slice(0,10).map(x=><div key={x.id}><span>{dateLabel(x.date)}</span><b>{fmtMin(rangeMins(x.morningStart,x.morningEnd)+rangeMins(x.afternoonStart,x.afternoonEnd))}</b><button className="trash" onClick={()=>update(s=>({...s,declared:s.declared.filter(q=>q.id!==x.id)}))}>Supprimer</button></div>)}</div></section>}

function EditDialog({store,edit,close,update}:{store:Store;edit:{kind:"shift"|"drive";id:string};close:()=>void;update:(f:(s:Store)=>Store,m?:string)=>void}){const item=edit.kind==="shift"?store.shifts.find(x=>x.id===edit.id):store.drives.find(x=>x.id===edit.id);const[start,setStart]=useState(item?.start.slice(0,16)||"");const[end,setEnd]=useState(item?.end?.slice(0,16)||"");const d=edit.kind==="drive"?item as Drive:undefined;const[km1,setKm1]=useState(d?.startKm.toString()||"");const[km2,setKm2]=useState(d?.endKm?.toString()||"");return <div className="modal"><div className="dialog"><h3>Modifier la session</h3><label>Début<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Fin<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label>{d&&<><label>Km départ<input type="number" value={km1} onChange={e=>setKm1(e.target.value)}/></label><label>Km arrivée<input type="number" value={km2} onChange={e=>setKm2(e.target.value)}/></label></>}<div className="dialog-actions"><button className="secondary" onClick={close}>Annuler</button><button className="primary" onClick={()=>{update(s=>edit.kind==="shift"?({...s,shifts:s.shifts.map(x=>x.id===edit.id?{...x,start:new Date(start).toISOString(),end:end?new Date(end).toISOString():undefined}:x)}):({...s,drives:s.drives.map(x=>x.id===edit.id?{...x,start:new Date(start).toISOString(),end:end?new Date(end).toISOString():undefined,startKm:+km1,endKm:km2?+km2:undefined}:x)}),"Session modifiée");close()}}>Enregistrer</button></div></div></div>}

function ServiceChecksPage({store,update}:{store:Store;update:(f:(s:Store)=>Store,m?:string)=>void}){const done=store.serviceChecks.filter(x=>x.checked).length;return <><section className="cards three"><Metric title="Prises prévues" value={String(store.serviceChecks.length)} text="services du jour"/><Metric title="Vérifiées" value={`${done}/${store.serviceChecks.length}`} text="contrôlées ce matin"/><Metric title="À contrôler" value={String(store.serviceChecks.length-done)} text="reste à vérifier"/></section><section className="panel"><div className="panel-head"><div><span className="kicker">Exploitation</span><h3>Prises de service du jour</h3></div><button className="primary" onClick={()=>update(s=>({...s,serviceChecks:s.serviceChecks.map(x=>({...x,checked:true,hawk:"Vérifiée"}))}),"Toutes les prises ont été vérifiées")}>Tout vérifier</button></div><div className="table service-table"><div className="tr th"><span>OK</span><span>PS</span><span>QUB</span><span>Conducteur</span><span>Service</span><span>Véhicule</span><span>Hawk</span></div>{store.serviceChecks.map(x=><div className="tr" key={x.id}><input type="checkbox" checked={x.checked} onChange={()=>update(s=>({...s,serviceChecks:s.serviceChecks.map(q=>q.id===x.id?{...q,checked:!q.checked,hawk:!q.checked?"Vérifiée":"À contrôler"}:q)}))}/><b>{x.time}</b><span>{x.qub}</span><span>{x.driver}</span><b>{x.service}</b><span>{x.vehicle||"À affecter"}</span><span className={x.checked?"check-ok":"check-warn"}>{x.hawk}</span></div>)}</div></section></>}
function DeparturesPage({store}:{store:Store}){const rows=[...store.serviceChecks].sort((a,b)=>a.time.localeCompare(b.time));return <section className="panel"><div className="panel-head"><div><span className="kicker">60 prochaines minutes</span><h3>Prochains départs</h3></div><span className="pill good">{rows.length} départs</span></div><div className="departure-list">{rows.map(x=><article key={x.id}><time>{x.time}</time><div><b>{x.service}</b><p>{x.driver} · {x.vehicle||"Véhicule à affecter"}</p></div><span className={x.checked?"pill good":"pill"}>{x.checked?"Prise validée":"À contrôler"}</span></article>)}</div></section>}
function SaePage({store}:{store:Store}){return <><section className="cards three"><Metric title="Véhicules suivis" value={String(store.serviceChecks.filter(x=>x.vehicle).length)} text="affectations du jour"/><Metric title="En service" value={String(store.serviceChecks.filter(x=>x.checked).length)} text="prises validées"/><Metric title="Alertes" value={String(store.serviceChecks.filter(x=>!x.checked).length)} text="contrôles nécessaires"/></section><section className="panel"><div className="panel-head"><div><span className="kicker">SAE personnel</span><h3>Suivi des véhicules</h3></div><span className="pill">Mode local</span></div><div className="sae-grid">{store.serviceChecks.filter(x=>x.vehicle).map((x,i)=><article key={x.id} className="sae-card"><div><span className="line-badge">{x.service.match(/(12|16|17|P140)/)?.[0]||"QUB"}</span><b>{x.vehicle}</b></div><h4>{x.service}</h4><p>Destination : à récupérer depuis la base SAE</p><p>Prochain arrêt : configuration Notion requise</p><footer><span>{x.checked?"● Allumé":"○ Non vérifié"}</span><time>{x.time}</time></footer></article>)}</div></section></>}
function ParkingPage({store,update}:{store:Store;update:(f:(s:Store)=>Store,m?:string)=>void}){const depots=[...new Set(store.parking.map(x=>x.depot))];return <>{depots.map(depot=><section className="panel" key={depot}><div className="panel-head"><div><span className="kicker">Stationnement</span><h3>{depot}</h3></div><span className="pill good">{store.parking.filter(x=>x.depot===depot).length} emplacements</span></div><div className="parking-grid">{store.parking.filter(x=>x.depot===depot).map(x=><article className="parking-spot" key={x.id}><b>{x.spot}</b><select value={x.vehicle} onChange={e=>update(s=>({...s,parking:s.parking.map(q=>q.id===x.id?{...q,vehicle:e.target.value}:q)}),"Stationnement modifié")}><option value="">Libre</option>{store.settings.vehicles.map(v=><option key={v}>{v}</option>)}</select><span className={x.vehicle?"occupied":"free"}>{x.vehicle?"Occupé":"Libre"}</span></article>)}</div></section>)}</>}

function Stats({stats}:{stats:ReturnType<typeof calcStats>}){return <><section className="stats-stack"><StatCard title="Aujourd’hui" d={stats.today}/><StatCard title="Cette semaine" d={stats.week}/><StatCard title="Ce mois" d={stats.month}/><StatCard title="Cette année" d={stats.year}/></section><section className="panel"><h3>Totaux journaliers</h3><div className="table"><div className="tr th"><span>Date</span><span>Service</span><span>Conduite</span><span>Kilomètres</span></div>{stats.days.map(x=><div className="tr" key={x.date}><span>{dateLabel(x.date)}</span><b>{fmtMin(x.work)}</b><b>{fmtMin(x.drive)}</b><b>{x.km} km</b></div>)}</div></section></>}
function StatCard({title,d}:{title:string;d:{work:number;drive:number;km:number;due:number;balance:number}}){const pc=d.due?Math.min(100,Math.round(d.work/d.due*100)):100;return <article className="stat-card"><span>{title}</span><div className="stat-main"><strong>{fmtMin(d.work)}</strong><small>/ {fmtMin(d.due)} attendues</small></div><div className="progress"><i style={{width:`${pc}%`}}/></div><div className={d.balance>=0?"balance pos":"balance neg"}>{fmtMin(d.balance,true)} par rapport au prévu <em>{pc}%</em></div><footer><div><span>Conduite</span><b>{fmtMin(d.drive)}</b></div><div><span>Kilomètres</span><b>{d.km} km</b></div></footer></article>}

function FuelPage({store,update}:{store:Store;update:(f:(s:Store)=>Store,m?:string)=>void}){const rows=useMemo(()=>fuelCalc(store.fuels),[store.fuels]);return <><section className="cards three"><Metric title="Pleins enregistrés" value={String(store.fuels.length)} text="tous véhicules"/><Metric title="Volume total" value={`${store.fuels.reduce((t,x)=>t+x.litres,0).toFixed(1)} L`} text="carburant enregistré"/><Metric title="Consommation moyenne" value={rows.some(x=>x.consumption)?`${(rows.filter(x=>x.consumption).reduce((t,x)=>t+(x.consumption||0),0)/rows.filter(x=>x.consumption).length).toFixed(1)} L/100`:"—"} text="entre pleins successifs"/></section><section className="panel"><h3>Pleins de carburant</h3><div className="table fuel-table"><div className="tr th"><span>Date</span><span>Véhicule</span><span>Km</span><span>Litres</span><span>Consommation</span><span></span></div>{rows.map(x=><div className="tr" key={x.id}><span>{dateTime(x.date)}</span><b>{x.vehicle}</b><span>{x.km}</span><span>{x.litres.toFixed(2)} L</span><span>{x.consumption?`${x.consumption.toFixed(1)} L/100 km`:"Premier relevé"}</span><button className="trash" onClick={()=>confirm("Supprimer ce plein ?")&&update(s=>({...s,fuels:s.fuels.filter(q=>q.id!==x.id)}),"Plein supprimé")}>Supprimer</button></div>)}</div></section></>}

function LeavePage({store,update}:{store:Store;update:(f:(s:Store)=>Store,m?:string)=>void}){const[date,setDate]=useState(localDate()),[type,setType]=useState<DayOff["type"]>("Férié"),[label,setLabel]=useState("");return <section className="panel"><h3>Jours non travaillés</h3><p className="muted">Un jour férié, congé ou repos ne génère pas de déficit d’heures attendu.</p><div className="form-grid leave-form"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Type<select value={type} onChange={e=>setType(e.target.value as DayOff["type"])}><option>Férié</option><option>Congé payé</option><option>Repos</option></select></label><label>Libellé<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Ex. Lundi de Pâques"/></label><button className="primary" onClick={()=>update(s=>({...s,daysOff:[{id:uid(),date,type,label},...s.daysOff.filter(x=>x.date!==date)]}),"Jour ajouté")}>Ajouter</button></div><div className="compact-list">{store.daysOff.map(x=><div key={x.id}><span>{dateLabel(x.date)} · {x.type} {x.label&&`· ${x.label}`}</span><button className="trash" onClick={()=>update(s=>({...s,daysOff:s.daysOff.filter(q=>q.id!==x.id)}))}>Supprimer</button></div>)}</div></section>}

function SettingsPage({store,update}:{store:Store;update:(f:(s:Store)=>Store,m?:string)=>void}){const [s,setS]=useState(store.settings);const [newV,setNewV]=useState("");const save=()=>update(x=>({...x,settings:s}),"Paramètres enregistrés");const fields:[keyof Settings,string][]=[["notionVehicle","Base véhicules – Parc Océlorn"],["notionDrivers","Base conducteurs"],["notionLmjt","LMJV PS Services"],["notionWednesday","Mercredi PS Services"],["notionHoliday","Samedi + Vacances"],["notionStops","Arrêts QUB / BreizhStops"],["notionServiceChecks","Prises de service"],["notionSae","SAE"],["notionParking","Stationnement / Parking"],["notionWork","Sessions de travail"],["notionDrive","Sessions de conduite"],["notionFuel","Pleins de carburant"]];return <><section className="panel"><h3>Soldes initiaux</h3><div className="form-grid settings-grid"><label>Compteur d’heures actuel (minutes)<input type="number" value={s.overtimeMinutes} onChange={e=>setS({...s,overtimeMinutes:+e.target.value})}/><small>Ex. 690 pour +11h30</small></label><label>Date de départ du nouveau suivi<input type="date" value={s.balanceStartDate} onChange={e=>setS({...s,balanceStartDate:e.target.value})}/><small>Le solde saisi sert de point de départ à cette date.</small></label><label>Congés N-1<input type="number" step=".5" value={s.leaveN1} onChange={e=>setS({...s,leaveN1:+e.target.value})}/></label><label>Congés N<input type="number" step=".5" value={s.leaveN} onChange={e=>setS({...s,leaveN:+e.target.value})}/></label></div></section><section className="panel"><h3>Bases Notion</h3><p className="muted">Collez les liens complets ou les identifiants. Ils seront conservés dans le navigateur.</p><div className="settings-fields">{fields.map(([k,l])=><label key={String(k)}>{l}<input value={String(s[k])} onChange={e=>setS({...s,[k]:e.target.value})} placeholder="https://www.notion.so/..."/></label>)}</div></section><section className="panel"><h3>Véhicules disponibles</h3><div className="vehicle-add"><input value={newV} onChange={e=>setNewV(e.target.value.toUpperCase())} placeholder="Immatriculation"/><button className="primary" onClick={()=>{if(newV&&!s.vehicles.includes(newV)){setS({...s,vehicles:[...s.vehicles,newV].sort()});setNewV("")}}}>Ajouter</button></div><div className="chips">{s.vehicles.map(v=><span key={v}>{v}<button onClick={()=>setS({...s,vehicles:s.vehicles.filter(x=>x!==v)})}>×</button></span>)}</div></section><button className="primary save-settings" onClick={save}>Enregistrer tous les paramètres</button><section className="panel warning-box"><h3>Connexion Notion</h3><p>Cette version fonctionne immédiatement en stockage local. Pour lire et modifier automatiquement des bases Notion privées, il faudra ajouter un Worker Cloudflare sécurisé avec le jeton de l’intégration Notion. Un simple lien de base ne suffit pas et le jeton ne doit jamais être placé dans le navigateur.</p></section></>}

function calcStats(store:Store,now:number){
 const current=new Date(); current.setHours(23,59,59,999);
 const weekA=startOfWeek(current),weekB=new Date(current);
 const monthA=new Date(current.getFullYear(),current.getMonth(),1),monthB=new Date(current);
 const yearA=new Date(current.getFullYear(),0,1),yearB=new Date(current);
 const startDate=new Date(`${store.settings.balanceStartDate||localDate()}T00:00:00`);
 const dayData=new Map<string,{work:number;drive:number;km:number}>();
 store.shifts.forEach(x=>{const d=localDate(new Date(x.start));const z=dayData.get(d)||{work:0,drive:0,km:0};z.work+=mins(ms(x.start,x.end,now));dayData.set(d,z)});
 store.drives.forEach(x=>{const d=localDate(new Date(x.start));const z=dayData.get(d)||{work:0,drive:0,km:0};z.drive+=mins(ms(x.start,x.end,now));if(x.endKm!==undefined)z.km+=Math.max(0,x.endKm-x.startKm);dayData.set(d,z)});
 store.declared.forEach(x=>{const z=dayData.get(x.date)||{work:0,drive:0,km:0};if(!z.work)z.work=rangeMins(x.morningStart,x.morningEnd)+rangeMins(x.afternoonStart,x.afternoonEnd);dayData.set(x.date,z)});
 const days=[...dayData.entries()].map(([date,x])=>({date,...x})).sort((a,b)=>b.date.localeCompare(a.date));
 const aggregate=(a:Date,b:Date)=>{const filtered=days.filter(x=>inRange(`${x.date}T12:00:00`,a,b));const work=filtered.reduce((t,x)=>t+x.work,0),drive=filtered.reduce((t,x)=>t+x.drive,0),km=filtered.reduce((t,x)=>t+x.km,0);const weekdays=countWeekdays(a,b);const offs=store.daysOff.filter(x=>inRange(`${x.date}T12:00:00`,a,b)).filter(x=>{const d=new Date(`${x.date}T12:00:00`).getDay();return d>=1&&d<=5}).length;const due=Math.max(0,(weekdays-offs)*DAILY);return{work,drive,km,due,balance:work-due}};
 const td=dayData.get(localDate())||{work:0,drive:0,km:0};const todayOff=store.daysOff.some(x=>x.date===localDate());
 return {today:{...td,due:todayOff?0:DAILY,balance:td.work-(todayOff?0:DAILY)},week:aggregate(weekA,weekB),month:aggregate(monthA,monthB),year:aggregate(yearA,yearB),sinceStart:aggregate(startDate,current),days}
}
function countWeekdays(a:Date,b:Date){let n=0;const d=new Date(a);while(d<=b){const x=d.getDay();if(x>=1&&x<=5)n++;d.setDate(d.getDate()+1)}return n}
function fuelCalc(fuels:Fuel[]){const by=new Map<string,Fuel[]>();fuels.forEach(f=>by.set(f.vehicle,[...(by.get(f.vehicle)||[]),f]));const out:(Fuel&{consumption?:number})[]=[];by.forEach(xs=>{const s=[...xs].sort((a,b)=>a.km-b.km);s.forEach((x,i)=>{const p=s[i-1],dist=p?x.km-p.km:0;out.push({...x,consumption:dist>0?x.litres/dist*100:undefined})})});return out.sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime())}

export default App;
